import {
  mysqlTable,
  serial,
  varchar,
  text,
  int,
  tinyint,
  timestamp,
} from "drizzle-orm/mysql-core";

export const entries = mysqlTable("entries", {
  id: serial("id").primaryKey(),
  region: varchar("region", { length: 50 }).notNull(),
  recordDate: varchar("record_date", { length: 20 }).notNull(),
  orgName: varchar("org_name", { length: 200 }).notNull(),
  orgAddress: varchar("org_address", { length: 500 }).default(""),
  city: varchar("city", { length: 50 }).notNull(),
  platform: varchar("platform", { length: 20 }).notNull(),
  accountType: varchar("account_type", { length: 50 }).notNull(),
  accountName: varchar("account_name", { length: 200 }).notNull(),
  contentType: varchar("content_type", { length: 20 }).notNull(),
  product: varchar("product", { length: 100 }).notNull(),
  publishDate: varchar("publish_date", { length: 20 }).default(""),
  contentLink: varchar("content_link", { length: 500 }).default(""),
  approveStatus: varchar("approve_status", { length: 20 }).notNull().default("待审核"),
  approveDate: varchar("approve_date", { length: 20 }).default(""),
  approver: varchar("approver", { length: 100 }).default(""),
  dataCollectDate: varchar("data_collect_date", { length: 20 }).default(""),
  screenshotUploaded: tinyint("screenshot_uploaded").default(0),
  screenshotData: text("screenshot_data"),
  readCount: int("read_count").default(0),
  likes: int("likes").default(0),
  favorites: int("favorites").default(0),
  comments: int("comments").default(0),
  interactCount: int("interact_count").default(0),
  tier: varchar("tier", { length: 20 }),
  rewardCount: int("reward_count").default(0),
  sendStatus: varchar("send_status", { length: 20 }).notNull().default("待发放"),
  sendDate: varchar("send_date", { length: 20 }),
  trackingNo: varchar("tracking_no", { length: 100 }),
  received: tinyint("received").default(0),
  receiveDate: varchar("receive_date", { length: 20 }),
  note: text("note"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
