import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";

export const entries = sqliteTable("entries", {
  id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
  region: text("region").notNull(),
  recordDate: text("record_date").notNull(),
  orgName: text("org_name").notNull(),
  orgAddress: text("org_address").default(""),
  city: text("city").notNull(),
  platform: text("platform").notNull(),
  accountType: text("account_type").notNull(),
  accountName: text("account_name").notNull(),
  contentType: text("content_type").notNull(),
  product: text("product").notNull(),
  publishDate: text("publish_date").default(""),
  contentLink: text("content_link").default(""),
  approveStatus: text("approve_status").notNull().default("待审核"),
  approveDate: text("approve_date").default(""),
  approver: text("approver").default(""),
  dataCollectDate: text("data_collect_date").default(""),
  screenshotUploaded: integer("screenshot_uploaded").default(0),
  screenshotData: text("screenshot_data").default(""),
  readCount: integer("read_count").default(0),
  likes: integer("likes").default(0),
  favorites: integer("favorites").default(0),
  comments: integer("comments").default(0),
  interactCount: integer("interact_count").default(0),
  tier: text("tier").default(""),
  rewardCount: integer("reward_count").default(0),
  sendStatus: text("send_status").notNull().default("待发放"),
  sendDate: text("send_date").default(""),
  trackingNo: text("tracking_no").default(""),
  received: integer("received").default(0),
  receiveDate: text("receive_date").default(""),
  note: text("note").default(""),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(() => new Date()),
});
